name: check

on: [workflow_call]

jobs:
  clang-checks:
    runs-on: ubuntu-latest
    container: oraclelinux:9
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Install dependencies
      uses: ./.github/actions/install-dependencies
      with:
        clang-tools: true
    - name: make format-check
      run: make format
    - name: make tidy-check
      run: make tidy

  editor-config:
    runs-on: ubuntu-latest
    container: mstruebing/editorconfig-checker
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Check editorconfig
      run: ec --exclude .git

  include-orders:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Run include-order-checker
      run: "! grep -r -A 10 '#include <' src/ include/ | grep -B 10 '#include \"'"

  cppcheck:
    uses: ./.github/workflows/cppcheck.yml
  
  doxygen:
    runs-on: ubuntu-latest
    container: oraclelinux:9
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Install dependencies
      uses: ./.github/actions/install-dependencies
    - name: Install doxygen
      run: |
        dnf config-manager --set-enabled ol9_codeready_builder
        dnf install -y doxygen
    - name: make doxygen
      run: make doxygen
    - name: upload Doxygen artifact
      uses: actions/upload-artifact@v4
      with:
        name: doxygen
        path: ./build/doc/doxygen/html
        retention-days: 7
